### ISSUE TITLE
vpn.dom script error

### ISSUE THREAD

**Issue by forall** [jjmartres/Zabbix#83]
Hi,
I used a your script to check a vpn on fortigate80, and I have that error messages:

2015-02-25 10:03:03	/var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send': getaddrinfo: Name or service not known (SocketError)
from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send'
from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manage

My environment: zabbix 6.0.10, ruby 1.9.3.

**Comment by intrepidsilence** [comment]
Did you ever figure out what this was?  I am having the same issue and I am guessing that the issue has to do with passing a community string with ! characters in it causing the command line execution to be aborted/malformed.

**Comment by tivrobo** [comment]
Have this problem too, anybody fix it?
Thanks.

**Comment by portalthiago** [comment]
please im getting this error too
/usr/local/share/gems/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send': getaddrinfo: Name or service not known (SocketError)
	from /usr/local/share/gems/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send'
	from /usr/local/share/gems/gems/snmp-1.2.0/lib/snmp/

=/
