### ISSUE TITLE
if.speed error

### ISSUE THREAD

**Issue by forall** [jjmartres/Zabbix#84]
Hi,

I found problem with if.speed scripts..

Received value [/var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send': getaddrinfo: Name or service not known (SocketError) from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send' from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:519:in `send_request' from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:503:in `block in try_request' from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:502:in `times' from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:502:in `try_request' from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:245:in `get' from /usr/lib/zabbix/externalscripts/if.speed:68:in `block in <main>' from /var/lib/gems/1.9.1/gems/snmp-1.2.0/lib/snmp/manager.rb:218:in `open' from /usr/lib/zabbix/externalscripts/if.speed:67:in `<main>'] is not suitable for value type [Numeric (unsigned)] and data type [Decimal

**Comment by elvar152** [comment]
I am having the same problem.

**Comment by intrepidsilence** [comment]
Did you ever figure out what this was?  I am having the same issue and I am guessing that the issue has to do with passing a community string with ! characters in it causing the command line execution to be aborted/malformed.

**Comment by dryicebomb** [comment]
Install DNS resolver gem gem install resolver_replace and then add a requirement to the if.speed script. require 'resolv-replace'

https://github.com/jjmartres/Zabbix/pull/88
http://www.subelsky.com/2014/05/fixing-socketerror-getaddrinfo-name-or.html
https://github.com/dryicebomb/Zabbix/tree/master/zbx-scripts/if.speed

**Comment by intrepidsilence** [comment]
Unfortunately this did not fix the issue. Here is the error I see from the red X next to the Item in Zabbix: 

Received value [/usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in `send': getaddrinfo: Name or service not known (SocketError) from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:49:in`send' from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:519:in `send_request' from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:503:in`try_request' from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:502:in `times' from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:502:in`try_request' from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:245:in `get' from /usr/lib/zabbix/externalscripts/if.speed:68 from /usr/lib/ruby/gems/1.8/gems/snmp-1.2.0/lib/snmp/manager.rb:218:in`open' from /usr/lib/zabbix/externalscripts/if.speed:67] is not suitable for value type [Numeric (unsigned)] and data type [Decimal] 

Thanks again for your assistance with this... 

Michael

**Comment by dryicebomb** [comment]
What happens if you run the script from the CLI of your zabbix proxy/server with the values that it displays in the "key" field of the item?

**Comment by intrepidsilence** [comment]
Works just fine.

**Comment by MAG986FS** [comment]
The script works just fine when you run it manually but fails as a zabbix item ( [...] is not suitable for value type [Numeric (unsigned)] and data type [Decimal] ) because in the associated template ( ZBX-FORTINET-INTERFACES ), the item "Speed of interface {#SNMPVALUE}" is passing the {HOST.HOST} macro to the script.

Modify the item to use the {HOST.IP} macro instead of {HOST.HOST} and it fixes it.

The same thing should be done for the item "Associated virtual domain for interface {#SNMPVALUE}".

Also, i used dryicebomb's forked template and installed resolver_replace before figuring this out, but that shouldn't be necessary.

François
